/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.redes.vistas;

import com.redes.bebidas.Bebida;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author geoge
 */
public class VistaReporte extends javax.swing.JFrame {

    private List<Bebida> listBebidas;

    /**
     * Creates new form VistaReporte
     */
    public VistaReporte() {
        initComponents();
        listBebidas = new ArrayList<Bebida>();
        limpiarTabla();
    }

    public void addValoresTabla(Bebida bebida) {
        DefaultTableModel modelo = (DefaultTableModel) jTablaVentas.getModel();
        Object[] fila = new Object[4];
        fila[0] = bebida.getNombre();
        fila[1] = bebida.getPrecio();
        fila[2] = bebida.getNumBebida();
        fila[3] = bebida.getPrecio() * bebida.getNumBebida();
        modelo.addRow(fila);
        listBebidas.add(bebida);
        jTablaVentas.setModel(modelo);
    }

    public void limpiarTabla() {
        DefaultTableModel modelo = (DefaultTableModel) jTablaVentas.getModel();
        modelo.setRowCount(0);
        jTablaVentas.setModel(modelo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBebidas = new javax.swing.JComboBox<>();
        jbtnBusqueda = new javax.swing.JButton();
        jbtnMostarTodo = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablaVentas = new javax.swing.JTable();

        setTitle("Reporte de Ventas");

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setText("Reporte de Ventas");

        jLabel2.setText("Bebida");

        jComboBebidas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Coca Cola", "Fanta", "Sprite" }));
        jComboBebidas.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBebidasItemStateChanged(evt);
            }
        });

        jbtnBusqueda.setText("Busqueda");

        jbtnMostarTodo.setText("Mostrar Todo");
        jbtnMostarTodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnMostarTodoActionPerformed(evt);
            }
        });

        jTablaVentas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nombre Bebida", "Costo por Bebida", "Numero Bebidas Vendidas", "Ventas Totales"
            }
        ));
        jScrollPane1.setViewportView(jTablaVentas);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(288, 288, 288)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBebidas, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbtnBusqueda)
                        .addGap(18, 18, 18)
                        .addComponent(jbtnMostarTodo)))
                .addGap(42, 42, 42))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBebidas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnBusqueda)
                    .addComponent(jbtnMostarTodo))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(290, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBebidasItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBebidasItemStateChanged
        if (evt.getItem().equals("Coca Cola")) {
            limpiarTabla();
            addValoresTabla(listBebidas.get(0));
        } else if (evt.getItem().equals("Fanta")) {
            limpiarTabla();
            addValoresTabla(listBebidas.get(1));
        } else if (evt.getItem().equals("Sprite")) {
            limpiarTabla();
            addValoresTabla(listBebidas.get(2));
        }

    }//GEN-LAST:event_jComboBebidasItemStateChanged

    private void jbtnMostarTodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnMostarTodoActionPerformed
        // TODO add your handling code here:
        limpiarTabla();
        addValoresTabla(listBebidas.get(0));
        addValoresTabla(listBebidas.get(1));
        addValoresTabla(listBebidas.get(2));
    }//GEN-LAST:event_jbtnMostarTodoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaReporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaReporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaReporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaReporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaReporte().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBebidas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTablaVentas;
    private javax.swing.JButton jbtnBusqueda;
    private javax.swing.JButton jbtnMostarTodo;
    // End of variables declaration//GEN-END:variables
}
